[package]
name = "cargo-publish-workspace-rename"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["dep",
#"dep2"
]

[workspace.dependencies]
dep = { package = "prefix-dep", version = "0.1.0", path = "dep" }

[dependencies]
dep.workspace = true
